### ISSUE TITLE
Test Error: Unable to open file *.bam. Exiting

### ISSUE THREAD

**Issue by wanhui5867** [a2iEditing/RNAEditingIndexer#12]
Hi,

I was going to test the tool with the test_resource data in the installation directory. I catched an error "Unable to open file *.bam. Exiting".

The commond I used as following:
`
./RNAEditingIndex -d ./TestResources/BAMs -f _sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam -l test_log_dir -o test_out_dir -os test_summary_dir --genome hg38 -rb ./TestResources/AnnotationAndRegions/ucscHg38Alu.OnlyChr1.bed.gz --refseq ./TestResources/AnnotationAndRegions/ucscHg38RefSeqCurated.OnlyChr1.bed.gz --snps ./TestResources/AnnotationAndRegions/ucscHg38CommonGenomicSNPs150.OnlyChr1.bed.gz --genes_expression ./TestResources/AnnotationAndRegions/ucscHg38GTExGeneExpression.OnlyChr1.bed.gz --verbose --stranded --paired
`

Then it raised "Unable to open file" errors, part errors were listed as follows:

> Error: Unable to open file ./TestResources/BAMs/BAMs/SRR5962201/SRR5962201_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
> [E::hts_open_format] Failed to open file test_out_dir/BAMs/SRR5962201/SRR5962201/SRR5962201_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam
> samtools sort: failed to create "test_out_dir/BAMs/SRR5962201/SRR5962201/SRR5962201_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam": No such file or directory
> [2019-11-21 15:45:40,235] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962201; Going To Error Step: Step_1_backup
> Error: Unable to open file ./TestResources/BAMs/BAMs/SRR5962209/SRR5962209_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
> [E::hts_open_format] Failed to open file test_out_dir/BAMs/SRR5962209/SRR5962209/SRR5962209_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam
> samtools sort: failed to create "test_out_dir/BAMs/SRR5962209/SRR5962209/SRR5962209_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam": No such file or directory
> [2019-11-21 15:45:40,354] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962209; Going To Error Step: Step_1_backup
> Error: Unable to open file ./TestResources/BAMs/BAMs/SRR5962217/SRR5962217_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
> [E::hts_open_format] Failed to open file test_out_dir/BAMs/SRR5962217/SRR5962217/SRR5962217_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam

I checked the test bam files that they are accessible, excuatable, readable and writable. I installed the tool in  Ubuntu 18.04.1 LTS and all the installation seem successful.

**Comment by twmccart** [comment]
I also have this issue.

**Comment by stelmanAM** [comment]
Same thing here when trying to run sample data as documented (see below when pwd = TestResources). Similar results using my own data.

> ../RNAEditingIndex -d BAMs -f _sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam --genome hg38 -rb AnnotationAndRegions/ucscHg38Alu.OnlyChr1.bed.gz --refseq AnnotationAndRegions/ucscHg38RefSeqCurated.OnlyChr1.bed.gz --snps AnnotationAndRegions/ucscHg38CommonGenomicSNPs150.OnlyChr1.bed.gz --genes_expression AnnotationAndRegions/ucscHg38GTExGeneExpression.OnlyChr1.bed.gz --verbose --stranded --paired
Error: Unable to open file BAMs/BAMs/SRR5962217/SRR5962217_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2019-12-11 11:46:24,096] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962217; Going To Error Step: Step_-1
Failed To Run On BAMs/BAMs/SRR5962217/SRR5962217_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
Error: Unable to open file BAMs/BAMs/SRR5962219/SRR5962219_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2019-12-11 11:46:24,143] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962219; Going To Error Step: Step_-1
Failed To Run On BAMs/BAMs/SRR5962219/SRR5962219_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
Error: Unable to open file BAMs/BAMs/SRR5962209/SRR5962209_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2019-12-11 11:46:24,198] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962209; Going To Error Step: Step_-1
Failed To Run On BAMs/BAMs/SRR5962209/SRR5962209_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
Error: Unable to open file BAMs/BAMs/SRR5962201/SRR5962201_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2019-12-11 11:46:24,250] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962201; Going To Error Step: Step_-1
Failed To Run On BAMs/BAMs/SRR5962201/SRR5962201_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
[2019-12-11 11:46:24,260] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 11-12-2019-19.cnf
[2019-12-11 11:46:24,260] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 11-12-2019-19.cnf
Error: Type checker found wrong number of fields while tokenizing data line.
Perhaps you have extra TAB at the end of your line? Check with "cat -t"
[2019-12-11 11:47:52,887] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962209! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './BAMs/SRR5962209/SRR5962209/SRR5962209_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2019-12-11 11:47:52,889] A2IEditingIndex ERROR    Failed Processing of SRR5962209!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2019-12-11 11:47:53,096] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962201! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './BAMs/SRR5962201/SRR5962201/SRR5962201_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2019-12-11 11:47:53,103] A2IEditingIndex ERROR    Failed Processing of SRR5962201!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2019-12-11 11:47:53,347] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962219! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './BAMs/SRR5962219/SRR5962219/SRR5962219_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2019-12-11 11:47:53,350] A2IEditingIndex ERROR    Failed Processing of SRR5962219!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2019-12-11 11:47:53,482] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962217! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './BAMs/SRR5962217/SRR5962217/SRR5962217_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2019-12-11 11:47:53,484] A2IEditingIndex ERROR    Failed Processing of SRR5962217!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2019-12-11 11:47:53,590] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./BAMs/SRR5962201/SRR5962201/SRR5962201_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2019-12-11 11:47:53,590] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./BAMs/SRR5962219/SRR5962219/SRR5962219_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2019-12-11 11:47:53,590] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./BAMs/SRR5962209/SRR5962209/SRR5962209_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2019-12-11 11:47:53,590] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./BAMs/SRR5962217/SRR5962217/SRR5962217_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2019-12-11 11:47:53,591] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./ucscHg38Genome.fa.GenomeIndex.jsd

**Comment by hoholee** [comment]
Hi,
Has anyone figured out how to fix this? I got some similar errors when I tried to run the test:

```
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[E::hts_open_format] Failed to open file ./cmpileup_output/BAMs/SRR5962201/SRR5962201/SRR5962201_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam
samtools sort: failed to create "./cmpileup_output/BAMs/SRR5962201/SRR5962201/SRR5962201_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam": No such file or directory
[2020-02-03 11:16:51,018] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962201; Going To Error Step: Step_-1
Failed To Run On /home/jul307/software/RNAEditingIndexer/TestResources/BAMs/BAMs/SRR5962201/SRR5962201_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[E::hts_open_format] Failed to open file ./cmpileup_output/BAMs/SRR5962219/SRR5962219/SRR5962219_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam
samtools sort: failed to create "./cmpileup_output/BAMs/SRR5962219/SRR5962219/SRR5962219_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam": No such file or directory
[2020-02-03 11:16:51,515] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962219; Going To Error Step: Step_-1
Failed To Run On /home/jul307/software/RNAEditingIndexer/TestResources/BAMs/BAMs/SRR5962219/SRR5962219_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[E::hts_open_format] Failed to open file ./cmpileup_output/BAMs/SRR5962209/SRR5962209/SRR5962209_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam
samtools sort: failed to create "./cmpileup_output/BAMs/SRR5962209/SRR5962209/SRR5962209_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam": No such file or directory
[2020-02-03 11:16:52,725] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962209; Going To Error Step: Step_-1
Failed To Run On /home/jul307/software/RNAEditingIndexer/TestResources/BAMs/BAMs/SRR5962209/SRR5962209_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[E::hts_open_format] Failed to open file ./cmpileup_output/BAMs/SRR5962217/SRR5962217/SRR5962217_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam
samtools sort: failed to create "./cmpileup_output/BAMs/SRR5962217/SRR5962217/SRR5962217_region_ucscHg38Alu.OnlyChr1.bed.gz_alignments.bam": No such file or directory
[2020-02-03 11:16:55,397] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962217; Going To Error Step: Step_-1
Failed To Run On /home/jul307/software/RNAEditingIndexer/TestResources/BAMs/BAMs/SRR5962217/SRR5962217_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
[2020-02-03 11:16:55,403] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 03-02-2020-19.cnf
[2020-02-03 11:16:55,403] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 03-02-2020-19.cnf
Error: Type checker found wrong number of fields while tokenizing data line.
Perhaps you have extra TAB at the end of your line? Check with "cat -t"
[2020-02-03 11:17:48,140] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962219! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './cmpileup_output/BAMs/SRR5962219/SRR5962219/SRR5962219_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2020-02-03 11:17:48,141] A2IEditingIndex ERROR    Failed Processing of SRR5962219!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2020-02-03 11:17:48,226] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962201! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './cmpileup_output/BAMs/SRR5962201/SRR5962201/SRR5962201_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2020-02-03 11:17:48,227] A2IEditingIndex ERROR    Failed Processing of SRR5962201!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2020-02-03 11:17:48,314] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962209! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './cmpileup_output/BAMs/SRR5962209/SRR5962209/SRR5962209_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2020-02-03 11:17:48,315] A2IEditingIndex ERROR    Failed Processing of SRR5962209!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2020-02-03 11:17:48,410] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962217! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 907, in get_stranded_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './cmpileup_output/BAMs/SRR5962217/SRR5962217/SRR5962217_ucscHg38Alu.OnlyChr1.bed.gz_mpileup_strand_1.cmpileup'
[2020-02-03 11:17:48,411] A2IEditingIndex ERROR    Failed Processing of SRR5962217!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 806, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 589, in output_sample_stranded
KeyError: '+'
[2020-02-03 11:17:48,472] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./cmpileup_output/BAMs/SRR5962201/SRR5962201/SRR5962201_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2020-02-03 11:17:48,472] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./cmpileup_output/BAMs/SRR5962209/SRR5962209/SRR5962209_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2020-02-03 11:17:48,473] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./cmpileup_output/ucscHg38Genome.fa.GenomeIndex.jsd
[2020-02-03 11:17:48,473] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./cmpileup_output/BAMs/SRR5962217/SRR5962217/SRR5962217_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
[2020-02-03 11:17:48,473] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./cmpileup_output/BAMs/SRR5962219/SRR5962219/SRR5962219_ucscHg38Alu.OnlyChr1.bed.gz_mpileup.cmpileup
```

**Comment by drupani** [comment]
Hi, 
has anyone fixed the above issues ? I have the same issue of being unable to open the bam file.

**Comment by guilhermetabordaribas** [comment]
Hi,
I have this same issue. I'm running on docker image.

**Comment by alnfedorov** [comment]
Hi all, I made it to work by specifying absolute paths. Here is an example to setup and run the pipeline with Docker:
```bash
docker build -t RNAEditingIndexer https://raw.githubusercontent.com/a2iEditing/RNAEditingIndexer/master/Dockerfile
docker run -v $(pwd):/data --rm -it RNAEditingIndexer bash
RNAEditingIndex -d /data/bam -f markdup.sorted.bam --genome mm10
```
Here I assumed that the raw data is placed in the `bam` folder and all files have `markdup.sorted.bam` postfix.

One might also get `Number of records read = 0` error, which in my case meant that I need to [reheader](https://www.biostars.org/p/13462/) bam files to change chromosomes notations(`1 -> chr1`).
