### ISSUE TITLE
docker run No Samples Were Found To Run On! Exiting...

### ISSUE THREAD

**Issue by wanhui5867** [a2iEditing/RNAEditingIndexer#13]
Hi,

I have also installed the tool in my Mac (Mojave 10.14.6) by using docker. This is my first time to use docker, so when I run failed I don't know that it's my wrong usage or anything else. My processes as following:

#Step1: build the image
`
 cd ~/biosoftware/
 git clone https://github.com/a2iEditing/RNAEditingIndexer.git
 cd RNAEditingIndexer/
 # run docker desktop
 docker image build -t aie:v1 .
`

#Step2: test after seeing "Done build."
`
docker run aie:v1 RNAEditingIndex -h
`
# it printed the usage, then I tried to test the TestResources data by the following command
```
docker run -v ~/biosoftware/RNAEditingIndexer/TestResources/BAMs/BAMs/SRR5962217:/data/bams:ro -v ~/biosoftware/RNAEditingIndexer:/data/output:rw aie:v1 RNAEditingIndex -d /data/bams -l ~/biosoftware/RNAEditingIndexer/test_logs_dir -o ~/biosoftware/RNAEditingIndexer/test_cmpileups -os ~/biosoftware/RNAEditingIndexer/Test_summary_dir --genome hg38
```
# it exits soon and raises the Warings
2019-11-21 18:19:42,165] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 21-11-2019-18.cnf
[2019-11-21 18:19:42,165] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 21-11-2019-18.cnf
[2019-11-21 18:19:42,165] A2IEditingIndex WARNING  No Samples Were Found To Run On! Exiting...

**Comment by bounlu** [comment]
I have the same problem without docker version:

```
./RNAEditingIndex -d /software/RNAEditingIndexer-master/TestResources/BAMs -f _sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam -l logs -o /software/RNAEditingIndexer-master/cmpileup -os /software/RNAEditingIndexer-master/summary --genome hg38 -rb /software/RNAEditingIndexer-master/TestResources/AnnotationAndRegions/ucscHg38Alu.OnlyChr1.bed.gz --refseq /software/RNAEditingIndexer-master/TestResources/AnnotationAndRegions/ucscHg38RefSeqCurated.OnlyChr1.bed.gz --snps /software/RNAEditingIndexer-master/TestResources/AnnotationAndRegions/ucscHg38CommonGenomicSNPs150.OnlyChr1.bed.gz --genes_expression /software/RNAEditingIndexer-master/TestResources/AnnotationAndRegions/ucscHg38GTExGeneExpression.OnlyChr1.bed.gz --verbose --stranded --paired

[2019-11-27 10:04:37,110] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 27-11-2019-02.cnf
[2019-11-27 10:04:37,110] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 27-11-2019-02.cnf
[2019-11-27 10:04:37,110] A2IEditingIndex WARNING  No Samples Were Found To Run On! Exiting...
```

**Comment by bounlu** [comment]
I had the same error, and realized that it happens due to the existence of the output folders. Remove them and rerun which should fix the issue. In your case it will be:

`rm -R test_logs_dir test_cmpileups Test_summary_dir`

**Comment by wanhui5867** [comment]
@bounlu Thanks for your suggestion. But those output folders did not build in my work path after run RNAEditingIndex command.

**Comment by shalomhillelroth** [comment]
Hi,

Sorry for the belated reply.

Can you kindly check what you specified for the -f option? 
If your are using the test files, you **must** change the value for the suffix (-f parameter, see issue #8 for a little more details). 

As for what @bounlu suggested, let me elaborate a bit on this - whenever a file is processed, a flag (matching the file's name) is created in the logs directory. If the flags exists - the file won't be processed in any future runs. This enables you to easily resume partially failed\ stopped runs and also to run multiple instances on the same inputs (this way you can split the load between machines, as the output is appended)

Best wishes.

Shalom Hillel Roth

**Comment by bounlu** [comment]
@wanhui5867 if you are still having problems, you can try it on our portal as I have just integrated `RNAEditingIndexer` as part of **RNA-Editing** pipeline with many thanks to the developers for their collaboration:

[CSI NGS Portal](https://csibioinfo.nus.edu.sg/csingsportal)

**Comment by wanhui5867** [comment]
@shalomhillelroth  Hi, thanks for your help, I added `-f "_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam"` parameter, and it runs. But it seems that my RAM  (16 G) is not enough so that it raises java.lang.OutOfMemoryError, as following:
`GenerateIndex - Starting!
Running: bedtools getfasta -name -bedOut -fi '/bin/AEI/RNAEditingIndexer/Resources/Genomes/HomoSapiens/ucscHg38Genome.fa' -bed '/bin/AEI/RNAEditingIndexer/Resources/Regions/HomoSapiens/ucscHg38Alu.bed.gz'
GenerateIndex - Indexing FASTA Records!
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1969)
	at java.lang.String.subSequence(String.java:2003)
	at java.util.regex.Pattern.split(Pattern.java:1233)
	at java.lang.String.split(String.java:2380)
	at java.lang.String.split(String.java:2422)
	at EditingIndexJavaUtils.BEDGenomeIndexer.GenerateIndex(BEDGenomeIndexer.java:54)
	at EditingIndexJavaUtils.BEDGenomeIndexer.main(BEDGenomeIndexer.java:117)
	at EditingIndexJavaUtils.EditingIndexBEDUtils.main(EditingIndexBEDUtils.java:30)
[2019-12-05 09:40:05,314] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962201; Going To Error Step: Step_-1
Failed To Run On /data/bams/BAMs/SRR5962201/SRR5962201_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam!
[2019-12-05 09:40:05,319] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 05-12-2019-09.cnf
[2019-12-05 09:40:05,319] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 05-12-2019-09.cnf`

T T

@bounlu Your CSI NGS Portal is a very excellent tool. I tried to use it, but it seems that can not upload BAM files to only run AEI calculation, right? If it can run the independent analysis that would be perfect. Thanks for your effort.

**Comment by bounlu** [comment]
@wanhui5867 On the portal only fastq files are accepted as the starting point for all the pipelines to keep the alignment standard and optimized, as well as to avoid failure due to the errors on the bam aligned by the user. However, for AEI calculation I also use STAR with the suggested parameter change in the paper "--outFilterMatchNminOverLread 0.95", so actually you can just upload your raw fastq files and submit to RNA-Editing pipeline to get the ideal AEI for all the samples without any hassle. hope this helps.
