### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jalalsiddiqui** [a2iEditing/RNAEditingIndexer#18]
I tried increasing the memory but to no avail.  What is causing this ValueError for the test data set?

Any help will be appreciated.  BTW has anyone gotten this to work?

[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
                #Bases to trim from each side : 5
 
Number of records read = 76230
Number of records written = 76230
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
                #Bases to trim from each side : 5
 
Number of records read = 76338
Number of records written = 76338
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
                #Bases to trim from each side : 5
[mpileup] 1 samples in 1 input files
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
                #Bases to trim from each side : 5
 
Number of records read = 62293
Number of records written = 62293
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
                #Bases to trim from each side : 5
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
                #Bases to trim from each side : 5
 
Number of records read = 63750
Number of records written = 63750
 
Number of records read = 106797
Number of records written = 106797
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
                #Bases to trim from each side : 5
[mpileup] 1 samples in 1 input files
 
Number of records read = 123921
Number of records written = 123921
Arguments in effect:
                Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
                Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
                #Bases to trim from each side : 5
 
Number of records read = 103573
Number of records written = 103573
[mpileup] 1 samples in 1 input files
 
Number of records read = 130933
Number of records written = 130933
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[2020-04-21 13:34:34,322] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 21-04-2020-17.cnf
[2020-04-21 13:34:34,323] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 21-04-2020-17.cnf
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1341, in <module>
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1166, in main
  File "Tools/EditingIndex/DataConverters/RefSeqGenesCoverter.py", line 101, in load_refseq_bed
ValueError: too many values to unpack
[182468] Failed to execute script A2IEditingIndex

**Comment by bounlu** [comment]
If you are having problems, alternatively, you can use RNA-Editing pipeline on CSI NGS Portal:

https://github.com/a2iEditing/RNAEditingIndexer/issues/13#issuecomment-561713668

**Comment by shalomhillelroth** [comment]
Hi, 

Sorry for the very belayed answer, with the whole COVID-19 happening I have very limited access to my computer.

Can you kindly attach the log and the stdout? 

Best,

Shalom Hillel Roth

**Comment by jalalsiddiqui** [comment]
@bounlu 
I can look up the alternate pipeline as well.  

@shalomhillelroth 
The log and stdout are as below.

-bash-4.2$ cat test_rei_10cores.sh.e10032064
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
[bam_sort_core] merging from 0 files and 10 in-memory blocks...
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
	#Bases to trim from each side : 5

Number of records read = 76230
Number of records written = 76230
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962217/SRR5962217_sampled/SRR5962217_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
	#Bases to trim from each side : 5

Number of records read = 76338
Number of records written = 76338
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
	#Bases to trim from each side : 5
[mpileup] 1 samples in 1 input files
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
	#Bases to trim from each side : 5

Number of records read = 62293
Number of records written = 62293
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962209/SRR5962209_sampled/SRR5962209_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
	#Bases to trim from each side : 5
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_1.bam.trimmed_5.bam
	#Bases to trim from each side : 5

Number of records read = 63750
Number of records written = 63750

Number of records read = 106797
Number of records written = 106797
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962219/SRR5962219_sampled/SRR5962219_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
	#Bases to trim from each side : 5
[mpileup] 1 samples in 1 input files

Number of records read = 123921
Number of records written = 123921
Arguments in effect:
	Input file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam
	Output file : /fs/project/PAS1348/RNAEditingIndex_test/output_directory/BAMs/SRR5962201/SRR5962201_sampled/SRR5962201_sampled_region_ucscHg38RefSeqCurated.OnlyChr1.bed.gz_alignments_strand_2.bam.trimmed_5.bam
	#Bases to trim from each side : 5

Number of records read = 103573
Number of records written = 103573
[mpileup] 1 samples in 1 input files

Number of records read = 130933
Number of records written = 130933
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[2020-04-21 13:34:34,322] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 21-04-2020-17.cnf
[2020-04-21 13:34:34,323] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 21-04-2020-17.cnf
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1341, in <module>
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1166, in main
  File "Tools/EditingIndex/DataConverters/RefSeqGenesCoverter.py", line 101, in load_refseq_bed
ValueError: too many values to unpack
[182468] Failed to execute script A2IEditingIndex

For the stdout, I have

-bash-4.2$ cat test_rei_10cores.sh.o10032064 | head
GenerateIndex - Starting!
Running: bedtools getfasta -name -bedOut -fi '/fs/project/PAS1348/Software/RNAEditingIndexer/Resources/Genomes/HomoSapiens/ucscHg38Genome.fa' -bed '/fs/project/PAS1348/Software/RNAEditingIndexer/TestResources/AnnotationAndRegions/ucscHg38RefSeqCurated.OnlyChr1.bed.gz'
GenerateIndex - Indexing FASTA Records!
GenerateIndex - Done Converting, Outputted to /fs/project/PAS1348/RNAEditingIndex_test/output_directory/ucscHg38Genome.fa.GenomeIndex.jsd
PileupToCount - Warning: Found Coverage Out Of index! (Ignoring)
PileupToCount - Warning: Found Coverage Out Of index! (Ignoring)
PileupToCount - Warning: Found Coverage Out Of index! (Ignoring)
PileupToCount - Warning: Found Coverage Out Of index! (Ignoring)
PileupToCount - Warning: Found Coverage Out Of index! (Ignoring)
PileupToCount - Warning: Found Coverage Out Of index! (Ignoring)

It keeps going down with PileupToCount.

No worries about the belated response.  Take your time.  I appreciate all your help.

**Comment by jalalsiddiqui** [comment]
One question.  Do you think this could be on my end (the cluster I am running)?  If so I can work with our supercomputing group at my university.

**Comment by itamary1** [comment]
we ran this tools on thousands of samples on AWS machines with 22GB of memory (one sample each), its should be sufficient(30GB in the worst cases).
