### ISSUE TITLE
bedtoolspath error

### ISSUE THREAD

**Issue by Juliaae** [a2iEditing/RNAEditingIndexer#21]
Hello,
I got an error with bedtoolspath error. I use the bedtools version whith 2.28(>2.26), but it told me No option 'bedtoolspath' in section: 'DEFAULT'.
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1341, in <module>
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1071, in main
  File "Tools/EditingIndex/A2IEditingIndex.py", line 1007, in load_resources_paths
  File "ConfigParser.py", line 618, in get
ConfigParser.NoOptionError: No option 'bedtoolspath' in section: 'DEFAULT'
[42410] Failed to execute script A2IEditingIndex

**Comment by Joey-xty** [comment]
I have the same issue with you, have you solved it later?

**Comment by aramanaccent** [comment]
@shalomhillelroth  I am having the same error too! If you have any ideas how to fix this please let me know.  I am using 
samtools=1.9
bedtools=2.27.1 
bamutil=1.0.14 &&
cyclus java-jdk=8.0.92 
python=2.7.17

**Comment by itamary1** [comment]
make sure you run the initialization successfully - 
cd ./RNAEditingIndexer

#configure installtion environmental variables (note the '.' !)
. ./configure.sh
make
