### ISSUE TITLE
AssertionError: Strand Calling In Stranded Library is Ambiguous! Skipping This Sample

### ISSUE THREAD

**Issue by sgomez0328** [a2iEditing/RNAEditingIndexer#31]
[21-08-26 22:07:49] EditingIndexProcessingSubprocessTCGA-13-0725-01A. CountPileupCoverter INFO     Found 166181 regions, 13784044 coverages in chromosomes: ['chrY',
 'chrX',
 'chr13',
 'chr12',
 'chr11',
 'chr10',
 'chr17',
 'chr16',
 'chr15',
 'chr14',
 'chr19',
 'chr18',
 'chr22',
 'chr20',
 'chr21',
 'chr7',
 'chr6',
 'chr5',
 'chr4',
 'chr3',
 'chr2',
 'chr1',
 'chr9',
 'chr8']
[21-08-26 22:07:49] EditingIndexProcessingSubprocessTCGA-13-0725-01A. A2IEditingIndex INFO     Done Loading Second Strand Coverage Data of TCGA-13-0725-01A.
[21-08-26 22:07:50] EditingIndexProcessingSubprocessTCGA-13-0725-01A. A2IEditingIndex ERROR    Failed Processing of TCGA-13-0725-01A.!
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 793, in load_and_process_sample
  File "Tools/EditingIndex/A2IEditingIndex.py", line 927, in get_stranded_strands_and_counts
AssertionError: Strand Calling In Stranded Library is Ambiguous! Skipping This Sample
[21-08-26 22:07:50] MainProcess A2IEditingIndex DEBUG    Acquired Semaphore, left 0

**Comment by ryrl9703** [comment]
> 

I have the same problem, have you solved it?

**Comment by umasstr** [comment]
Same issue here. Also concerning is that their test data reproducibly fails to run in the docker container.

**Comment by zhongzheng1999** [comment]
@umasstr @ryrl9703 @sgomez0328 I have the same problem, have you solved it?

**Comment by umasstr** [comment]
No unfortunately never got a response. The web tool also won't upload. Package is likely not maintained anymore...

**Comment by itamary1** [comment]
Apologies for the significant delay in our response — the student who was primarily responsible for this pipeline left the lab several years ago.

Regarding the error: as indicated in the output, this occurs when strand assignment fails because there is no strand to which a substantially larger number of reads is mapped. In other words, although the library is marked as stranded, the data itself does not show a clear strand preference, making strand selection ambiguous.

We recommend verifying that the data is indeed truly stranded in practice.
