### ISSUE TITLE
Cannot run test data

### ISSUE THREAD

**Issue by ryrl9703** [a2iEditing/RNAEditingIndexer#34]
../RNAEditingIndex -d ../TestResources/BAMs/BAMs --genome hg38 -f _sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam

Error: Unable to open file ../TestResources/BAMs/BAMs/SRR5962217/SRR5962217_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2021-09-15 15:45:57,824] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962217; Going To Error Step: Step_1_backup
Error: Unable to open file ../TestResources/BAMs/BAMs/SRR5962219/SRR5962219_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2021-09-15 15:45:57,865] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962219; Going To Error Step: Step_1_backup
Error: Unable to open file ../TestResources/BAMs/BAMs/SRR5962209/SRR5962209_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2021-09-15 15:45:57,906] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962209; Going To Error Step: Step_1_backup
Error: Unable to open file ../TestResources/BAMs/BAMs/SRR5962201/SRR5962201_sampled_with_0.1.Aligned.sortedByCoord.out.bam.AluChr1Only.bam. Exiting.
samtools sort: failed to read header from "-"
[2021-09-15 15:45:57,948] EIPipelineManger ERROR    Process: Editing_Index_Pipline_SRR5962201; Going To Error Step: Step_1_backup
[2021-09-15 15:45:57,950] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 15-09-2021-07.cnf
[2021-09-15 15:45:57,950] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove 15-09-2021-07.cnf
[2021-09-15 15:48:48,076] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962201! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 856, in get_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './SRR5962201/SRR5962201/SRR5962201_ucscHg38Alu.bed.gz_mpileup.cmpileup'
[2021-09-15 15:48:48,426] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962219! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 856, in get_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './SRR5962219/SRR5962219/SRR5962219_ucscHg38Alu.bed.gz_mpileup.cmpileup'
[2021-09-15 15:48:48,774] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962217! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 856, in get_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './SRR5962217/SRR5962217/SRR5962217_ucscHg38Alu.bed.gz_mpileup.cmpileup'
[2021-09-15 15:48:49,121] A2IEditingIndex ERROR    Failed Loading Coverage Data of SRR5962209! (Won't Delete cmpileup)
Traceback (most recent call last):
  File "Tools/EditingIndex/A2IEditingIndex.py", line 856, in get_strands_and_counts
  File "Tools/EditingIndex/DataConverters/CountPileupCoverter.py", line 69, in parse_count_pileup
IOError: [Errno 2] No such file or directory: './SRR5962209/SRR5962209/SRR5962209_ucscHg38Alu.bed.gz_mpileup.cmpileup'
[2021-09-15 15:48:49,327] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./SRR5962219/SRR5962219/SRR5962219_ucscHg38Alu.bed.gz_mpileup.cmpileup
[2021-09-15 15:48:49,327] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./SRR5962201/SRR5962201/SRR5962201_ucscHg38Alu.bed.gz_mpileup.cmpileup
[2021-09-15 15:48:49,328] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./SRR5962209/SRR5962209/SRR5962209_ucscHg38Alu.bed.gz_mpileup.cmpileup
[2021-09-15 15:48:49,328] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./ucscHg38Genome.fa.GenomeIndex.jsd
[2021-09-15 15:48:49,328] general_functions WARNING  GGPSResources.general_functions.remove_files Failed To Remove ./SRR5962217/SRR5962217/SRR5962217_ucscHg38Alu.bed.gz_mpileup.cmpileup

How should I solve this problem?

**Comment by izengyx** [comment]
same problem.

**Comment by itamary1** [comment]
Try it with samtools 1.9 and bedtools 2.26.0, or use our docker image
